### PR TITLE
Sylius 1.12.0

### PR DESCRIPTION
**Pull request by julienTroopers**
This Pull Request aims at making the bundle compatible with Sylius 1.12
I fixed any error I could find but I couldn't run the tests.

To be merged, it would require :
- [x]  a clean test run
- [x] remove older Sylius versions from composer.json (they can fallback to older releases)

Could anyone help for those 2 points ?

### CODE REVIEW

**Comment by xXNoceboXx** [comment]
@julienTroopers I create a pull requets on your fork: https://github.com/julienTroopers/RbacPlugin/pull/1

**Comment by julienTroopers** [comment]
Thanks a lot for your help !

**Comment by xXNoceboXx** [comment]
@bigboss86 can you review that please ?

**Comment by bigboss86** [comment]
Merged! Thanks!

**Pull request merged**
